### ISSUE TITLE
Hello World fails

### ISSUE THREAD

**Issue by rdebath** [spcutrell/brainfuck#1]
You're quite right, your loops have a type one bug (you don't skip over nested loops correctly),  in addition you've forgotten that your cells are signed. 

``` bf
>++++++++[-<+++++++++>]<.>[][<-]>+>-[+]++>++>+++[>[->+++<<+++>]<<]>-----.
>->+++..+++.>-.<<+[>[+>+]>>]<--------------.>>.+++.------.--------.>+.>+.
```

**Comment by spcutrell** [comment]
I finally got around to making these changes.  Thanks for putting an eye on it!
